//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.18444
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 之類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建 Visual Studio 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResWeb {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResWeb() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResWeb", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 C&apos;est La Vie 的當地語系化字串。
        /// </summary>
        internal static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ₱ 的當地語系化字串。
        /// </summary>
        internal static string CurrencySign {
            get {
                return ResourceManager.GetString("CurrencySign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 C&apos;est La Vie 的當地語系化字串。
        /// </summary>
        internal static string EngName {
            get {
                return ResourceManager.GetString("EngName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Server Error. Please contact the web manager. 的當地語系化字串。
        /// </summary>
        internal static string Err_ConnectionServerOut {
            get {
                return ResourceManager.GetString("Err_ConnectionServerOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Invalid E-mail Address 的當地語系化字串。
        /// </summary>
        internal static string Err_Field_Email_Format {
            get {
                return ResourceManager.GetString("Err_Field_Email_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Required 的當地語系化字串。
        /// </summary>
        internal static string Err_Field_Require {
            get {
                return ResourceManager.GetString("Err_Field_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Sorry, you have logged in. 的當地語系化字串。
        /// </summary>
        internal static string Err_LoginState {
            get {
                return ResourceManager.GetString("Err_LoginState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Fail. Please re-type your e-mail and password. 的當地語系化字串。
        /// </summary>
        internal static string Err_LoginUnCorrect {
            get {
                return ResourceManager.GetString("Err_LoginUnCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please log in first. 的當地語系化字串。
        /// </summary>
        internal static string Err_LogoutState {
            get {
                return ResourceManager.GetString("Err_LogoutState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The E-mail address has been registered. 的當地語系化字串。
        /// </summary>
        internal static string Err_MailHasExist {
            get {
                return ResourceManager.GetString("Err_MailHasExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The E-mail address has not been registered yet. 的當地語系化字串。
        /// </summary>
        internal static string Err_MailNotExist {
            get {
                return ResourceManager.GetString("Err_MailNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Wrong validation code 的當地語系化字串。
        /// </summary>
        internal static string Err_MembernNoValidCode {
            get {
                return ResourceManager.GetString("Err_MembernNoValidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 This member is unable to login. 的當地語系化字串。
        /// </summary>
        internal static string Err_MemberStateNotAllowLogin {
            get {
                return ResourceManager.GetString("Err_MemberStateNotAllowLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 該會員狀態已無法驗證，或已驗證完成。 的當地語系化字串。
        /// </summary>
        internal static string Err_MemberValidState {
            get {
                return ResourceManager.GetString("Err_MemberValidState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Not the same as above. Please check your password. 的當地語系化字串。
        /// </summary>
        internal static string Err_PasswordConfirm {
            get {
                return ResourceManager.GetString("Err_PasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please type at least 6 characters. 的當地語系化字串。
        /// </summary>
        internal static string Err_PasswordLength {
            get {
                return ResourceManager.GetString("Err_PasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Wrong password. 的當地語系化字串。
        /// </summary>
        internal static string Err_PasswordNotCorrect {
            get {
                return ResourceManager.GetString("Err_PasswordNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The password needs letters and numbers. 的當地語系化字串。
        /// </summary>
        internal static string Err_PasswordRule {
            get {
                return ResourceManager.GetString("Err_PasswordRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 You have paid. 的當地語系化字串。
        /// </summary>
        internal static string Err_PayHasFinished {
            get {
                return ResourceManager.GetString("Err_PayHasFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please type the password twice. 的當地語系化字串。
        /// </summary>
        internal static string Err_pwdHasBlank {
            get {
                return ResourceManager.GetString("Err_pwdHasBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Required 的當地語系化字串。
        /// </summary>
        internal static string Err_RequireData {
            get {
                return ResourceManager.GetString("Err_RequireData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Session Lost 的當地語系化字串。
        /// </summary>
        internal static string Err_SessionLost {
            get {
                return ResourceManager.GetString("Err_SessionLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Wrong validation code 的當地語系化字串。
        /// </summary>
        internal static string Err_ValideUnCorrect {
            get {
                return ResourceManager.GetString("Err_ValideUnCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Finish adding to the shopping cart. 的當地語系化字串。
        /// </summary>
        internal static string Info_AddCartItemOK {
            get {
                return ResourceManager.GetString("Info_AddCartItemOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Finish changing the quantity. 的當地語系化字串。
        /// </summary>
        internal static string Info_AmtChangeFinish {
            get {
                return ResourceManager.GetString("Info_AmtChangeFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please use these browsers: Chrome, Firefox or IE9 (or above). 的當地語系化字串。
        /// </summary>
        internal static string Info_Browerlimit {
            get {
                return ResourceManager.GetString("Info_Browerlimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Finish deleting the product. 的當地語系化字串。
        /// </summary>
        internal static string Info_ItemRemoveFinish {
            get {
                return ResourceManager.GetString("Info_ItemRemoveFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Finish updating the profile. 的當地語系化字串。
        /// </summary>
        internal static string Info_MemberDataModifyOK {
            get {
                return ResourceManager.GetString("Info_MemberDataModifyOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Thank you for registration, please check your e-mail box to activate the account. (Check your spam mail folder if you do not receive the mail.) 的當地語系化字串。
        /// </summary>
        internal static string Info_MemberRegistStep1 {
            get {
                return ResourceManager.GetString("Info_MemberRegistStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 You have not bought any items yet. 的當地語系化字串。
        /// </summary>
        internal static string Info_NoShoppingItem {
            get {
                return ResourceManager.GetString("Info_NoShoppingItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Finish changing the password. Please use the new password to login. 的當地語系化字串。
        /// </summary>
        internal static string Info_PasswordDataModifyOK {
            get {
                return ResourceManager.GetString("Info_PasswordDataModifyOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Password has been sent. Please check your e-mail box. 的當地語系化字串。
        /// </summary>
        internal static string Info_PWDResend {
            get {
                return ResourceManager.GetString("Info_PWDResend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 At least 6 chars with letters and numbers 的當地語系化字串。
        /// </summary>
        internal static string Info_PWD_Principle {
            get {
                return ResourceManager.GetString("Info_PWD_Principle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Order Send 的當地語系化字串。
        /// </summary>
        internal static string Info_Shopping_Finish {
            get {
                return ResourceManager.GetString("Info_Shopping_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 C&apos;est La Vie&lt;cestlaviediva_01@gmail.com&gt; 的當地語系化字串。
        /// </summary>
        internal static string MailAdmin {
            get {
                return ResourceManager.GetString("MailAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 [C&apos;est La Vie ] Thank You for Registration. 的當地語系化字串。
        /// </summary>
        internal static string MailSubjectAddMember {
            get {
                return ResourceManager.GetString("MailSubjectAddMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 [C&apos;est La Vielt Order Detail ] - Testing 的當地語系化字串。
        /// </summary>
        internal static string MailSubjectOrderInfo {
            get {
                return ResourceManager.GetString("MailSubjectOrderInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 [ C&apos;est La Vie ] Your Password 的當地語系化字串。
        /// </summary>
        internal static string MailSubjectPWDReSend {
            get {
                return ResourceManager.GetString("MailSubjectPWDReSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 [C&apos;est La Vie] Password Change 的當地語系化字串。
        /// </summary>
        internal static string MailSubjectRestPWD {
            get {
                return ResourceManager.GetString("MailSubjectRestPWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 http://cestlavie.fly.idv.tw 的當地語系化字串。
        /// </summary>
        internal static string PublicUrl {
            get {
                return ResourceManager.GetString("PublicUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 回首頁 的當地語系化字串。
        /// </summary>
        internal static string WebLayoutHome {
            get {
                return ResourceManager.GetString("WebLayoutHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 C&apos;est La Vie 的當地語系化字串。
        /// </summary>
        internal static string WebTitle {
            get {
                return ResourceManager.GetString("WebTitle", resourceCulture);
            }
        }
    }
}
