//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.18444
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 之類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建 Visual Studio 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Res", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 刪除 的當地語系化字串。
        /// </summary>
        internal static string Button_Delete {
            get {
                return ResourceManager.GetString("Button_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新增 的當地語系化字串。
        /// </summary>
        internal static string Button_Insert {
            get {
                return ResourceManager.GetString("Button_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 返回前頁 的當地語系化字串。
        /// </summary>
        internal static string Button_Return {
            get {
                return ResourceManager.GetString("Button_Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 搜尋 的當地語系化字串。
        /// </summary>
        internal static string Button_Search {
            get {
                return ResourceManager.GetString("Button_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確定 的當地語系化字串。
        /// </summary>
        internal static string Button_Sure {
            get {
                return ResourceManager.GetString("Button_Sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確定新增 的當地語系化字串。
        /// </summary>
        internal static string Button_Sure_Insert {
            get {
                return ResourceManager.GetString("Button_Sure_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確定修改 的當地語系化字串。
        /// </summary>
        internal static string Button_Sure_Modify {
            get {
                return ResourceManager.GetString("Button_Sure_Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 修改 的當地語系化字串。
        /// </summary>
        internal static string ColModify {
            get {
                return ResourceManager.GetString("ColModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 資料刪除完成 的當地語系化字串。
        /// </summary>
        internal static string Data_Delete_Success {
            get {
                return ResourceManager.GetString("Data_Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 資料新增完成 的當地語系化字串。
        /// </summary>
        internal static string Data_Insert_Success {
            get {
                return ResourceManager.GetString("Data_Insert_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 資料異動完成 的當地語系化字串。
        /// </summary>
        internal static string Data_Trans_Success {
            get {
                return ResourceManager.GetString("Data_Trans_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 資料更新完成 的當地語系化字串。
        /// </summary>
        internal static string Data_Update_Success {
            get {
                return ResourceManager.GetString("Data_Update_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 刪除資料! 的當地語系化字串。
        /// </summary>
        internal static string Info_Delete_Data {
            get {
                return ResourceManager.GetString("Info_Delete_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ＊為必填欄位 的當地語系化字串。
        /// </summary>
        internal static string Info_StarMustEdit {
            get {
                return ResourceManager.GetString("Info_StarMustEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確定刪除？ 的當地語系化字串。
        /// </summary>
        internal static string IsSureDelete {
            get {
                return ResourceManager.GetString("IsSureDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法登錄!狀態不符。 的當地語系化字串。
        /// </summary>
        internal static string Login_Err_Normal {
            get {
                return ResourceManager.GetString("Login_Err_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法登錄!請重輸入帳號或密碼。 的當地語系化字串。
        /// </summary>
        internal static string Login_Err_Password {
            get {
                return ResourceManager.GetString("Login_Err_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 已無燈位可供選擇! 的當地語系化字串。
        /// </summary>
        internal static string Log_Err_LightHasFinish {
            get {
                return ResourceManager.GetString("Log_Err_LightHasFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 該產品項目已被預訂中! 的當地語系化字串。
        /// </summary>
        internal static string Log_Err_LightHasOrdering {
            get {
                return ResourceManager.GetString("Log_Err_LightHasOrdering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 系統錯誤，無任何資料傳出。 的當地語系化字串。
        /// </summary>
        internal static string Log_Err_MustHaveData {
            get {
                return ResourceManager.GetString("Log_Err_MustHaveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確認密碼和新密碼不一致，請重新輸入。 的當地語系化字串。
        /// </summary>
        internal static string Log_Err_NewPasswordNotSure {
            get {
                return ResourceManager.GetString("Log_Err_NewPasswordNotSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新密碼和舊密碼不可相同。 的當地語系化字串。
        /// </summary>
        internal static string Log_Err_NewPasswordSame {
            get {
                return ResourceManager.GetString("Log_Err_NewPasswordSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 密碼不正確，請重新輸入。 的當地語系化字串。
        /// </summary>
        internal static string Log_Err_Password {
            get {
                return ResourceManager.GetString("Log_Err_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 該產品序號已存在。 的當地語系化字串。
        /// </summary>
        internal static string Log_Err_ProdSerialExists {
            get {
                return ResourceManager.GetString("Log_Err_ProdSerialExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ***系統提醒*** 的當地語系化字串。
        /// </summary>
        internal static string Log_Err_Title {
            get {
                return ResourceManager.GetString("Log_Err_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 地址資料未填寫。 的當地語系化字串。
        /// </summary>
        internal static string Log_Err_地址未輸入 {
            get {
                return ResourceManager.GetString("Log_Err_地址未輸入", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 姻緣燈需填寫完整生日資料。 的當地語系化字串。
        /// </summary>
        internal static string Log_Err_姻緣燈其生日資料需填寫完整 {
            get {
                return ResourceManager.GetString("Log_Err_姻緣燈其生日資料需填寫完整", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 安太歲需填入正確的農曆生日。 的當地語系化字串。
        /// </summary>
        internal static string Log_Err_安太歲生日不正確 {
            get {
                return ResourceManager.GetString("Log_Err_安太歲生日不正確", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 捐白米者需輸入捐白米的斤數。 的當地語系化字串。
        /// </summary>
        internal static string Log_Err_捐白米需輸入白米斤數 {
            get {
                return ResourceManager.GetString("Log_Err_捐白米需輸入白米斤數", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 捐金牌者需輸入金牌數目。 的當地語系化字串。
        /// </summary>
        internal static string Log_Err_捐金牌需輸入金牌數 {
            get {
                return ResourceManager.GetString("Log_Err_捐金牌需輸入金牌數", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 需選擇文殊梯次。 的當地語系化字串。
        /// </summary>
        internal static string Log_Err_文殊梯次未選擇 {
            get {
                return ResourceManager.GetString("Log_Err_文殊梯次未選擇", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 該項產品已經訂購，不可重複訂購。 的當地語系化字串。
        /// </summary>
        internal static string Log_Err_該產品已訂購 {
            get {
                return ResourceManager.GetString("Log_Err_該產品已訂購", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 保運類每張訂單最多只能6筆資料。 的當地語系化字串。
        /// </summary>
        internal static string Log_Err_超過保運項目6 {
            get {
                return ResourceManager.GetString("Log_Err_超過保運項目6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 訂單項目數量不可超過10項。 的當地語系化字串。
        /// </summary>
        internal static string Log_Err_超過訂購項目10 {
            get {
                return ResourceManager.GetString("Log_Err_超過訂購項目10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 訂單項目數量不可超過12項。 的當地語系化字串。
        /// </summary>
        internal static string Log_Err_超過訂購項目12 {
            get {
                return ResourceManager.GetString("Log_Err_超過訂購項目12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 捐香油錢需輸入捐獻金額不可為0。 的當地語系化字串。
        /// </summary>
        internal static string Log_Err_香油錢需輸入金額 {
            get {
                return ResourceManager.GetString("Log_Err_香油錢需輸入金額", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        internal static string NoMessage {
            get {
                return ResourceManager.GetString("NoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 搜尋 的當地語系化字串。
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 查詢無任何資料。 的當地語系化字串。
        /// </summary>
        internal static string Search_No_Data {
            get {
                return ResourceManager.GetString("Search_No_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇要刪除的列。 的當地語系化字串。
        /// </summary>
        internal static string Select_Delete_Data {
            get {
                return ResourceManager.GetString("Select_Delete_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 資料庫Table訂義模組未定義此欄位。 的當地語系化字串。
        /// </summary>
        internal static string Sys_Err_FieldNotExists {
            get {
                return ResourceManager.GetString("Sys_Err_FieldNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 系統錯誤，請聯絡管理員。 的當地語系化字串。
        /// </summary>
        internal static string Sys_Err_Title {
            get {
                return ResourceManager.GetString("Sys_Err_Title", resourceCulture);
            }
        }
    }
}
