//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcCore.Business.DB0
{
    using System;
    using System.Collections.Generic;
    public partial class m_Orders :BaseEntityTable {
    public int orders_id { get; set; }
    public string orders_sn { get; set; }
    public string orders_state { get; set; }
    public System.DateTime transation_date { get; set; }
    public int member_id { get; set; }
    public int member_detail_id { get; set; }
    public string member_name { get; set; }
    public Nullable<bool> gender { get; set; }
    public string tel { get; set; }
    public string zip { get; set; }
    public string address { get; set; }
    public string mobile { get; set; }
    public string email { get; set; }
    public string pay_style { get; set; }
    public Nullable<System.DateTime> pay_date { get; set; }
    public string bank_serial { get; set; }
    public int total { get; set; }
    public bool i_Hide { get; set; }
    public string i_InsertUserID { get; set; }
    public Nullable<int> i_InsertDeptID { get; set; }
    public Nullable<System.DateTime> i_InsertDateTime { get; set; }
    public string i_UpdateUserID { get; set; }
    public Nullable<int> i_UpdateDeptID { get; set; }
    public Nullable<System.DateTime> i_UpdateDateTime { get; set; }
    public string i_Lang { get; set; }
    }
}
