//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportDataApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders_Detail
    {
        public int orders_detail_id { get; set; }
        public string orders_sn { get; set; }
        public string product_sn { get; set; }
        public int member_detail_id { get; set; }
        public int Y { get; set; }
        public string product_name { get; set; }
        public int price { get; set; }
        public int amt { get; set; }
        public string member_name { get; set; }
        public string address { get; set; }
        public bool gender { get; set; }
        public string l_birthday { get; set; }
        public string born_time { get; set; }
        public string born_sign { get; set; }
        public string light_name { get; set; }
        public Nullable<int> race { get; set; }
        public Nullable<int> gold { get; set; }
        public Nullable<int> manjushri { get; set; }
        public bool i_Hide { get; set; }
        public string i_InsertUserID { get; set; }
        public Nullable<int> i_InsertDeptID { get; set; }
        public Nullable<System.DateTime> i_InsertDateTime { get; set; }
        public string i_UpdateUserID { get; set; }
        public Nullable<int> i_UpdateDeptID { get; set; }
        public Nullable<System.DateTime> i_UpdateDateTime { get; set; }
        public string i_Lang { get; set; }
    
        public virtual Orders Orders { get; set; }
    }
}
