//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportDataApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class 會員戶長資料
    {
        public 會員戶長資料()
        {
            this.會員資料表 = new HashSet<會員資料表>();
        }
    
        public int 戶長SN { get; set; }
        public string 電話 { get; set; }
        public string 郵遞區號 { get; set; }
        public string 地址 { get; set; }
        public string 姓名 { get; set; }
        public Nullable<System.DateTime> 建立時間 { get; set; }
    
        public virtual ICollection<會員資料表> 會員資料表 { get; set; }
    }
}
