//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportDataApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class 會員資料表
    {
        public int 序號 { get; set; }
        public int 戶長SN { get; set; }
        public bool Is戶長 { get; set; }
        public string 姓名 { get; set; }
        public string 電話區碼 { get; set; }
        public string 電話尾碼 { get; set; }
        public string 郵遞區號 { get; set; }
        public string 地址 { get; set; }
        public string 手機 { get; set; }
        public string 性別 { get; set; }
        public string 生日 { get; set; }
        public string 時辰 { get; set; }
        public string EMAIL { get; set; }
        public string 祈福事項 { get; set; }
        public string 生肖 { get; set; }
        public string 縣市 { get; set; }
        public string 鄉鎮 { get; set; }
        public Nullable<System.DateTime> 建立日期 { get; set; }
    
        public virtual 會員戶長資料 會員戶長資料 { get; set; }
    }
}
