//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportDataApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class 訂單主檔
    {
        public 訂單主檔()
        {
            this.訂單明細檔 = new HashSet<訂單明細檔>();
        }
    
        public long 訂單序號 { get; set; }
        public string 訂單編號 { get; set; }
        public int 會員編號 { get; set; }
        public string 申請人姓名 { get; set; }
        public string 申請人電話 { get; set; }
        public string 郵遞區號 { get; set; }
        public string 申請人地址 { get; set; }
        public string 申請人手機 { get; set; }
        public string 申請人性別 { get; set; }
        public string 申請人生日 { get; set; }
        public string 申請人EMAIL { get; set; }
        public int 總額 { get; set; }
        public string 付款方式 { get; set; }
        public Nullable<System.DateTime> 訂單時間 { get; set; }
        public Nullable<System.DateTime> 付款時間 { get; set; }
        public string 訂單狀態 { get; set; }
        public string 查詢序號 { get; set; }
        public string 付款方式名稱 { get; set; }
        public string 訂單狀態名稱 { get; set; }
        public string 銀行帳號 { get; set; }
        public System.DateTime 新增時間 { get; set; }
        public int 新增人員 { get; set; }
        public int 戶長SN { get; set; }
        public Nullable<bool> C_Hiden { get; set; }
        public Nullable<int> C_InsertUserID { get; set; }
        public Nullable<System.DateTime> C_InsertDateTime { get; set; }
        public Nullable<int> C_UpdateUserID { get; set; }
        public Nullable<System.DateTime> C_UpdateDateTime { get; set; }
    
        public virtual ICollection<訂單明細檔> 訂單明細檔 { get; set; }
    }
}
