//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportDataApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class 訂單明細檔
    {
        public long 訂單序號 { get; set; }
        public string 訂單編號 { get; set; }
        public string 產品編號 { get; set; }
        public int 會員編號 { get; set; }
        public int 年度 { get; set; }
        public string 產品名稱 { get; set; }
        public int 價格 { get; set; }
        public int 數量 { get; set; }
        public string 申請人姓名 { get; set; }
        public string 申請人地址 { get; set; }
        public string 申請人性別 { get; set; }
        public string 申請人生日 { get; set; }
        public string 申請人年齡 { get; set; }
        public string 申請人時辰 { get; set; }
        public string 申請人生肖 { get; set; }
        public Nullable<System.DateTime> 購買時間 { get; set; }
        public Nullable<System.DateTime> 付款時間 { get; set; }
        public string 祈福事項 { get; set; }
        public string 郵遞區號 { get; set; }
        public string 點燈位置 { get; set; }
        public string 經手人 { get; set; }
        public System.DateTime 新增時間 { get; set; }
        public int 新增人員 { get; set; }
        public int 白米 { get; set; }
        public int 金牌 { get; set; }
        public bool 異動標記 { get; set; }
        public int 文疏梯次 { get; set; }
        public Nullable<bool> C_Hiden { get; set; }
        public Nullable<int> C_InsertUserID { get; set; }
        public Nullable<System.DateTime> C_InsertDateTime { get; set; }
        public Nullable<int> C_UpdateUserID { get; set; }
        public Nullable<System.DateTime> C_UpdateDateTime { get; set; }
    
        public virtual 訂單主檔 訂單主檔 { get; set; }
    }
}
