//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Work.WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    using Newtonsoft.Json;
    public partial class AssemblyBatchChglog 
    {
        public int id { get; set; }
        public int y { get; set; }
        public string orders_sn { get; set; }
        public int orders_detail_id { get; set; }
        public string product_sn { get; set; }
        public string product_name { get; set; }
        public int member_detail_id { get; set; }
        public string member_name { get; set; }
        public Nullable<int> old_batch_sn { get; set; }
        public Nullable<int> old_light_id { get; set; }
        public string old_light_name { get; set; }
        public Nullable<int> new_batch_sn { get; set; }
        public Nullable<int> new_light_id { get; set; }
        public string new_light_name { get; set; }
        public string departed_name { get; set; }
        public string departed_address { get; set; }
        public string departed_qty { get; set; }
        public int C_InsertUserID { get; set; }
        public System.DateTime C_InsertDateTime { get; set; }
    
    	[JsonIgnore]
        public virtual AssemblyBatch NewBatch { get; set; }
    	[JsonIgnore]
        public virtual AssemblyBatch OldBatch { get; set; }
    	[JsonIgnore]
        public virtual Member_Detail 會員資料表 { get; set; }
    }
}
