//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Work.WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    using Newtonsoft.Json;
    public partial class Light_Site 
    {
        public int light_site_id { get; set; }
        public string light_name { get; set; }
        public int Y { get; set; }
        public string is_sellout { get; set; }
        public string product_sn { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<bool> C_Hiden { get; set; }
        public Nullable<int> C_InsertUserID { get; set; }
        public Nullable<System.DateTime> C_InsertDateTime { get; set; }
        public Nullable<int> C_UpdateUserID { get; set; }
        public Nullable<System.DateTime> C_UpdateDateTime { get; set; }
        public Nullable<int> C_LockUserID { get; set; }
        public Nullable<System.DateTime> C_LockDateTime { get; set; }
        public Nullable<bool> C_LockState { get; set; }
        public bool IsReject { get; set; }
    }
}
