//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Work.WebApp.Models
{
    using System;
    using System.Collections.Generic;
    public partial class m_Fortune_Light  {
    public int fortune_light_id { get; set; }
    public string order_sn { get; set; }
    public int Y { get; set; }
    public int member_detail_id { get; set; }
    public string member_name { get; set; }
    public string memo { get; set; }
    public bool tran_mark { get; set; }
    public int sort { get; set; }
    }
}
