//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Work.WebApp.Models
{
    using System;
    using System.Collections.Generic;
    public partial class m_Member  {
    public int member_id { get; set; }
    public string tel { get; set; }
    public string zip { get; set; }
    public string address { get; set; }
    public string householder { get; set; }
    public Nullable<System.DateTime> i_InsertDateTime { get; set; }
    public bool repeat_mark { get; set; }
    }
}
