//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Work.WebApp.Models
{
    using System;
    using System.Collections.Generic;
    public partial class m_TempleAccount  {
    public int temple_account_id { get; set; }
    public string product_name { get; set; }
    public string product_sn { get; set; }
    public System.DateTime tran_date { get; set; }
    public int price { get; set; }
    public int temple_member_id { get; set; }
    public int i_InsertUserID { get; set; }
    public string i_InsertUserName { get; set; }
    public System.DateTime i_InsertDateTime { get; set; }
    public Nullable<int> i_UpdateUserID { get; set; }
    public Nullable<System.DateTime> i_UpdateDateTime { get; set; }
    public string i_UpdateUserName { get; set; }
    }
}
