//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Work.WebApp.Models
{
    using System;
    using System.Collections.Generic;
    public partial class m_TempleMember  {
    public int temple_member_id { get; set; }
    public string sno { get; set; }
    public string member_name { get; set; }
    public string zip { get; set; }
    public string addr { get; set; }
    public string birthday { get; set; }
    public string mobile { get; set; }
    public string tel { get; set; }
    public bool is_close { get; set; }
    public Nullable<System.DateTime> last_attend_datetime { get; set; }
    public Nullable<System.DateTime> join_datetime { get; set; }
    public Nullable<System.DateTime> i_insertDateTime { get; set; }
    public string memo { get; set; }
    }
}
