//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Work.WebApp.Models
{
    using System;
    using System.Collections.Generic;
    public partial class m_Units  {
    public int units_id { get; set; }
    public string units_name { get; set; }
    public string 電子信箱 { get; set; }
    public string 地址 { get; set; }
    public string 電話 { get; set; }
    public string 傳真 { get; set; }
    public string 自動電話 { get; set; }
    public string 自動傳真 { get; set; }
    public string 代碼 { get; set; }
    public string 單位主管 { get; set; }
    public string 起始IP { get; set; }
    public string 結束IP { get; set; }
    public string IP { get; set; }
    public string 業務內容 { get; set; }
    public Nullable<double> 排序 { get; set; }
    }
}
