//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Work.WebApp.Models
{
    using System;
    using System.Collections.Generic;
    public partial class m_Users  {
    public int users_id { get; set; }
    public string account { get; set; }
    public string 密碼 { get; set; }
    public string users_name { get; set; }
    public string 住址 { get; set; }
    public string 家裡電話 { get; set; }
    public string 手機 { get; set; }
    public Nullable<System.DateTime> 生日 { get; set; }
    public Nullable<int> units_id { get; set; }
    public Nullable<int> 停權 { get; set; }
    public Nullable<int> 職稱代碼 { get; set; }
    public string 抬頭稱呼 { get; set; }
    public string 電子信箱 { get; set; }
    public Nullable<int> isadmin { get; set; }
    public string 使用IP { get; set; }
    public string MD5 { get; set; }
    }
}
