//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Work.WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    using Newtonsoft.Json;
    public partial class Orders_Detail 
    {
        public int orders_detail_id { get; set; }
        public string orders_sn { get; set; }
        public string product_sn { get; set; }
        public int member_detail_id { get; set; }
        public int Y { get; set; }
        public string product_name { get; set; }
        public int price { get; set; }
        public int amt { get; set; }
        public string member_name { get; set; }
        public string address { get; set; }
        public string gender { get; set; }
        public string l_birthday { get; set; }
        public string age { get; set; }
        public string born_time { get; set; }
        public string born_sign { get; set; }
        public Nullable<System.DateTime> 購買時間 { get; set; }
        public Nullable<System.DateTime> 付款時間 { get; set; }
        public string memo { get; set; }
        public string zip { get; set; }
        public string light_name { get; set; }
        public string 經手人 { get; set; }
        public System.DateTime i_InsertDateTime { get; set; }
        public int i_InsertUserID { get; set; }
        public int race { get; set; }
        public int gold { get; set; }
        public bool tran_mark { get; set; }
        public int manjushri { get; set; }
        public Nullable<bool> C_Hiden { get; set; }
        public Nullable<int> C_InsertUserID { get; set; }
        public Nullable<System.DateTime> C_InsertDateTime { get; set; }
        public Nullable<int> C_UpdateUserID { get; set; }
        public Nullable<System.DateTime> C_UpdateDateTime { get; set; }
        public Nullable<bool> is_reject { get; set; }
        public int detail_sort { get; set; }
        public string departed_address { get; set; }
        public string departed_name { get; set; }
        public Nullable<int> assembly_batch_sn { get; set; }
        public string departed_qty { get; set; }
    
    	[JsonIgnore]
        public virtual Orders Orders { get; set; }
    	[JsonIgnore]
        public virtual Product Product { get; set; }
    	[JsonIgnore]
        public virtual Member_Detail Member_Detail { get; set; }
    	[JsonIgnore]
        public virtual AssemblyBatch AssemblyBatch { get; set; }
    }
}
