//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Work.WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    using Newtonsoft.Json;
    public partial class Product 
    {
        public Product()
        {
            this.Orders_Detail = new HashSet<Orders_Detail>();
        }
    
        public string product_sn { get; set; }
        public string product_name { get; set; }
        public string category { get; set; }
        public bool isSelect { get; set; }
        public bool isLight { get; set; }
        public int price { get; set; }
        public Nullable<int> i_Hide { get; set; }
        public int 排序 { get; set; }
        public Nullable<int> C_InsertUserID { get; set; }
        public Nullable<System.DateTime> C_InsertDateTime { get; set; }
        public Nullable<int> C_UpdateUserID { get; set; }
        public Nullable<System.DateTime> C_UpdateDateTime { get; set; }
    
    	[JsonIgnore]
        public virtual ICollection<Orders_Detail> Orders_Detail { get; set; }
    }
}
