//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Work.WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    using Newtonsoft.Json;
    public partial class Reject_Detail 
    {
        public int reject_detail_id { get; set; }
        public int reject_id { get; set; }
        public int Y { get; set; }
        public int light_site_id { get; set; }
        public string light_name { get; set; }
        public int price { get; set; }
        public int member_detail_id { get; set; }
        public int orders_detail_id { get; set; }
    
    	[JsonIgnore]
        public virtual Reject Reject { get; set; }
    	[JsonIgnore]
        public virtual Member_Detail Member_Detail { get; set; }
    }
}
