//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Work.WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    using Newtonsoft.Json;
    public partial class Reject 
    {
        public Reject()
        {
            this.Reject_Detail = new HashSet<Reject_Detail>();
        }
    
        public int reject_id { get; set; }
        public System.DateTime reject_date { get; set; }
        public string orders_sn { get; set; }
        public int user_id { get; set; }
        public int total { get; set; }
        public int y { get; set; }
    
    	[JsonIgnore]
        public virtual ICollection<Reject_Detail> Reject_Detail { get; set; }
    	[JsonIgnore]
        public virtual Orders Orders { get; set; }
    }
}
