//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Work.WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    using Newtonsoft.Json;
    public partial class Wish_Light 
    {
        public System.Guid wish_light_id { get; set; }
        public int orders_detail_id { get; set; }
        public string order_sn { get; set; }
        public int Y { get; set; }
        public int member_detail_id { get; set; }
        public string member_name { get; set; }
        public int wish_id { get; set; }
        public string wish_text { get; set; }
        public int idx_sort { get; set; }
    
    	[JsonIgnore]
        public virtual Wish Wish { get; set; }
    	[JsonIgnore]
        public virtual Orders 訂單主檔 { get; set; }
    	[JsonIgnore]
        public virtual Member_Detail 會員資料表 { get; set; }
    }
}

